<<<<<<< HEAD
name: crewhub_mobile_v25
description: CrewHub V25 bilingual app with English and Romanian UI.
=======
name: crewhub_mobile_v7
description: CrewHub V7 bilingual app with English and Romanian UI.
>>>>>>> fc7dbce31452fcc05e5a2c33d11d97fc0d710a1d
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
<<<<<<< HEAD
  file_picker: ^8.1.7
=======
>>>>>>> fc7dbce31452fcc05e5a2c33d11d97fc0d710a1d

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
